### ISSUE TITLE
Package name

### ISSUE THREAD

**Issue by mschauer** [fmeulen/GuidedDAGExamples.jl#1]
The paper points to https://github.com/fmeulen/GuidedDAGExamples.jl, we could just move the repository there or fix it for next arxiv version

**Comment by fmeulen** [comment]
you mean the “.jl” extension should not be there?



---
Frank van der Meulen
Delft University of Technology
http://dutiosb.twi.tudelft.nl/~meulen/




On 11 Oct 2020, at 19.18, Moritz Schauer <notifications@github.com<mailto:notifications@github.com>> wrote:



The paper points to https://github.com/fmeulen/GuidedDAGExamples.jl<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_fmeulen_GuidedDAGExamples.jl&d=DwMCaQ&c=XYzUhXBD2cD-CornpT4QE19xOJBbRy-TBPLK0X9U2o8&r=7iF-JNHl-g2k0SDAFdfpFNwTGT5g4T8E90C3u4ODfF8&m=i5twnJUmGdnbnCKtYjUY8u8-p2CKwePdEF1IlhU1udQ&s=wdrgInc3-_2kLZm73h01Zwnd2y_hrazckqxkxqzS3c8&e=>, we could just move the repository there or fix it for next arxiv version

**Comment by mschauer** [comment]
Either here with extension or there without
